name: hogwarts_legacy
description: A App to you see information about hogwarts legacy

publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: '>=2.19.2 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  flutter_modular: ^5.0.3
  flutter_bloc: ^8.1.2
  dartz: ^0.10.1
  google_fonts: ^4.0.3

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0
  bloc_test: ^9.1.1
  mocktail: ^0.3.0


flutter:
  uses-material-design: true
  assets:
    - assets/images/

